/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HelperApps.ClassEditor;

import javax.swing.JTable;

/**
 *
 * @author jmd63115
 */
public class ClassEditorSpellsPerDayPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpellsPerDayPanel
     */
    public ClassEditorSpellsPerDayPanel() {
        initComponents();
    }

    public JTable getSpellsPerDayTable() {
        return spellsPerDayTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spellsPerDayTable = new javax.swing.JTable();

        setName("Spells Per Day"); // NOI18N

        jLabel1.setText("Spells per day (don't include domain spells)");

        spellsPerDayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Class level 1",  new Integer(3),  new Integer(1), null, null, null, null, null, null, null, null},
                {"Class level 2",  new Integer(4),  new Integer(2), null, null, null, null, null, null, null, null},
                {"Class level 3",  new Integer(4),  new Integer(2),  new Integer(1), null, null, null, null, null, null, null},
                {"Class level 4",  new Integer(5),  new Integer(3),  new Integer(2), null, null, null, null, null, null, null},
                {"Class level 5",  new Integer(5),  new Integer(3),  new Integer(2),  new Integer(1), null, null, null, null, null, null},
                {"Class level 6",  new Integer(5),  new Integer(3),  new Integer(3),  new Integer(2), null, null, null, null, null, null},
                {"Class level 7",  new Integer(6),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1), null, null, null, null, null},
                {"Class level 8",  new Integer(6),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2), null, null, null, null, null},
                {"Class level 9",  new Integer(6),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1), null, null, null, null},
                {"Class level 10",  new Integer(6),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2), null, null, null, null},
                {"Class level 11",  new Integer(6),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1), null, null, null},
                {"Class level 12",  new Integer(6),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2), null, null, null},
                {"Class level 13",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1), null, null},
                {"Class level 14",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2), null, null},
                {"Class level 15",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1), null},
                {"Class level 16",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2), null},
                {"Class level 17",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(2),  new Integer(1)},
                {"Class level 18",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3),  new Integer(2)},
                {"Class level 19",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(3),  new Integer(3)},
                {"Class level 20",  new Integer(6),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(5),  new Integer(4),  new Integer(4),  new Integer(4),  new Integer(4)}
            },
            new String [] {
                "Class Level", "Spell Level 0", "Spell Level 1", "Spell Level 2", "Spell Level 3", "Spell Level 4", "Spell Level 5", "Spell Level 6", "Spell Level 7", "Spell Level 8", "Spell Level 9"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(spellsPerDayTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable spellsPerDayTable;
    // End of variables declaration//GEN-END:variables
}
