package gui.inventory;

import character.Player;
import character.inventory.CarryingCapacity;
import character.inventory.CharacterInventory;
import interfaces.SaveStateReader;
import main.DataRetrievalManager;

/**
 *
 * @author Jacob
 */
public class GeneralInventoryPanel extends javax.swing.JPanel implements SaveStateReader {

    private CharacterInventory inventory;

    /**
     * Creates new form GeneralInventoryPanel
     */
    public GeneralInventoryPanel(Player player) {
        this.inventory = player.getInventory();
        initComponents();
        //Link this to load info from the inventory when this panel is selected and the data needs updating
        DataRetrievalManager.linkReader(this, inventory);
    }

    @Override
    public void loadInfo() {
        //If new data needs to be read
        if (DataRetrievalManager.isDataChanged(inventory, this)) {
            System.out.println("General inventory data updating.");
            double inventoryWeight = inventory.getInventoryWeight();
            inventoryWeightLabel.setText("" + inventoryWeight);
            double walletWeight = inventory.getWallet().getWeight();
            walletWeightLabel.setText("" + walletWeight);
            totalWeightLabel.setText("" + (inventoryWeight + walletWeight));
            CarryingCapacity.LoadThresholds currentLoadThresholds = inventory.getCurrentLoadThresholds();
            lightLoadLabel.setText("" + currentLoadThresholds.getLight());
            mediumLoadLabel.setText("" + currentLoadThresholds.getMedium());
            heavyLoadLabel.setText("" + currentLoadThresholds.getHeavy());
            CarryingCapacity.Load currentLoad = inventory.getCurrentLoad();
            currentLoadLabel.setText("" + currentLoad);
        }
        //Mark the data as read for this reader
        DataRetrievalManager.dataRead(inventory, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mediumLoadLabel = new javax.swing.JLabel();
        lightLoadLabel = new javax.swing.JLabel();
        heavyLoadLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        currentLoadLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        totalWeightLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        walletWeightLabel = new javax.swing.JLabel();
        inventoryWeightLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(456, 200));

        jLabel2.setText("Light load:");

        jLabel5.setText("Medium load:");

        jLabel6.setText("Heavy load:");

        mediumLoadLabel.setText("jLabel7");

        lightLoadLabel.setText("jLabel7");

        heavyLoadLabel.setText("jLabel7");

        jLabel10.setText("Current load:");

        currentLoadLabel.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heavyLoadLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lightLoadLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mediumLoadLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentLoadLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lightLoadLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mediumLoadLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(heavyLoadLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(currentLoadLabel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        totalWeightLabel.setText("jLabel2");

        jLabel1.setText("Total Weight:");

        walletWeightLabel.setText("jLabel6");

        inventoryWeightLabel.setText("jLabel5");

        jLabel4.setText("Wallet:");

        jLabel3.setText("Inventory:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(walletWeightLabel)
                            .addComponent(totalWeightLabel)
                            .addComponent(inventoryWeightLabel))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalWeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inventoryWeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(walletWeightLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentLoadLabel;
    private javax.swing.JLabel heavyLoadLabel;
    private javax.swing.JLabel inventoryWeightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lightLoadLabel;
    private javax.swing.JLabel mediumLoadLabel;
    private javax.swing.JLabel totalWeightLabel;
    private javax.swing.JLabel walletWeightLabel;
    // End of variables declaration//GEN-END:variables
}
