package gui.feats;

import character.CharacterFeats;
import character.Player;
import character.feats.Feat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import savestate.DataRetrievalManager;
import savestate.StateReader;

/**
 *
 * @author Japhez
 */
public class FeatPanel extends javax.swing.JPanel implements StateReader {

    private CharacterFeats feats;
    private DefaultListModel featModel;

    /**
     * Creates new form FeatPanel
     *
     * @param player
     */
    public FeatPanel(Player player) {
        this.feats = player.getFeats();
        initComponents();
        featModel = new DefaultListModel();
        featList.setModel(featModel);
        //Link to feats
        DataRetrievalManager.linkReader(this, player.getFeats());
    }

    /**
     * Reload displayed list of feats based off of player's list of feats.
     */
    private void updateList() {
        featModel.clear();
        ArrayList<Feat> feats = this.feats.getFeats();
        for (Feat f : feats) {
            featModel.addElement(f);
        }
    }

    private void updateDisplayedFeatInfo() {
        if (!featList.isSelectionEmpty()) {
            Feat selectedValue = (Feat) featList.getSelectedValue();
            featNameLabel.setText(selectedValue.getName());
            featDescriptionTextArea.setText(selectedValue.getDescription());
        } else {
            featNameLabel.setText("");
            featDescriptionTextArea.setText("");
        }
    }

    @Override
    public void loadInfo() {
        if (DataRetrievalManager.isDataChanged(feats, this)) {
            updateList();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        featNameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        featDescriptionTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featList = new javax.swing.JList();
        addFeatButton = new javax.swing.JButton();
        removeFeatButton = new javax.swing.JButton();
        exportFeatButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(543, 267));

        featNameLabel.setText("[feat name]");

        jLabel7.setText("Feat name:");

        jLabel11.setText("Feat description:");

        featDescriptionTextArea.setEditable(false);
        featDescriptionTextArea.setColumns(20);
        featDescriptionTextArea.setLineWrap(true);
        featDescriptionTextArea.setRows(5);
        featDescriptionTextArea.setWrapStyleWord(true);
        featDescriptionTextArea.setAutoscrolls(false);
        featDescriptionTextArea.setBorder(null);
        jScrollPane5.setViewportView(featDescriptionTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(featNameLabel)))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featNameLabel)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jLabel1.setText("Current feats:");

        featList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        featList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                featListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(featList);

        addFeatButton.setText("Add Feat");
        addFeatButton.setEnabled(false);

        removeFeatButton.setText("Remove Feat");
        removeFeatButton.setEnabled(false);

        exportFeatButton.setText("Export Feat");
        exportFeatButton.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeFeatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFeatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportFeatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addFeatButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeFeatButton)
                        .addGap(18, 18, 18)
                        .addComponent(exportFeatButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void featListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_featListValueChanged
        updateDisplayedFeatInfo();
    }//GEN-LAST:event_featListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFeatButton;
    private javax.swing.JButton exportFeatButton;
    private javax.swing.JTextArea featDescriptionTextArea;
    private javax.swing.JList featList;
    private javax.swing.JLabel featNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton removeFeatButton;
    // End of variables declaration//GEN-END:variables

}
