/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.proficiency;

import character.Player;
import character.proficiencies.WeaponProficiency;
import gui.ProficiencyPanel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Japhez
 */
public class AddWeaponProficiencyDialog extends javax.swing.JDialog {

    private Player character;
    private ProficiencyPanel parent;

    /**
     * Creates new form AddWeaponProficiencyDialog
     */
    public AddWeaponProficiencyDialog(ProficiencyPanel parent, Player character) {
        initComponents();
        this.parent = parent;
        this.character = character;
        initializeProficiencyLists();
    }

    private void initializeProficiencyLists() {
        //Get the character weapon proficiencies
        ArrayList<WeaponProficiency> characterProfs = character.getProficiencies().getWeaponProficiencyList();
        //Create a list model to attach to the each unknown proficiency list
        DefaultListModel simpleModel = new DefaultListModel();
        DefaultListModel martialModel = new DefaultListModel();
        DefaultListModel exoticModel = new DefaultListModel();

        ArrayList<WeaponProficiency> unknownSimpleProfs = WeaponProficiency.getSimpleWeapons();
        ArrayList<WeaponProficiency> unknownMartialProfs = WeaponProficiency.getMartialWeapons();
        ArrayList<WeaponProficiency> unknownExoticProfs = WeaponProficiency.getExoticWeapons();
        System.out.println(unknownExoticProfs.size());
        //Remove each known proficiency from the unknown simple proficiency list
        for (WeaponProficiency wp : characterProfs) {
            unknownSimpleProfs.remove(wp);
            unknownMartialProfs.remove(wp);
            unknownExoticProfs.remove(wp);

        }
        //Transfer data to models
        for (WeaponProficiency wp : unknownSimpleProfs) {
            simpleModel.addElement(wp);
        }
        simpleProficiencyList.setModel(simpleModel);
        for (WeaponProficiency wp : unknownMartialProfs) {
            martialModel.addElement(wp);
        }
        martialProficiencyList.setModel(martialModel);
        for (WeaponProficiency wp : unknownExoticProfs) {
            exoticModel.addElement(wp);
        }
        exoticProficiencyList.setModel(exoticModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        martialCancelButton = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        simplePlane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        simpleProficiencyList = new javax.swing.JList();
        simpleCancelButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        simpleSelectAllButton = new javax.swing.JButton();
        simpleDeselectAllButton = new javax.swing.JButton();
        simpleLearnProficiencyButton = new javax.swing.JButton();
        martialPlane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        martialProficiencyList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        martialSelectAllButton = new javax.swing.JButton();
        martialDeselectAllButton = new javax.swing.JButton();
        martialLearnProficiencyButton = new javax.swing.JButton();
        martiaCancelButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        exoticProficiencyList = new javax.swing.JList();
        exoticCancelButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        exoticSelectAllButton = new javax.swing.JButton();
        exoticDeselectAllButton = new javax.swing.JButton();
        exoticLearnProficiencyButton = new javax.swing.JButton();

        martialCancelButton.setText("Cancel");
        martialCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        simpleProficiencyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(simpleProficiencyList);

        simpleCancelButton.setText("Cancel");
        simpleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Unknown simple proficiencies:");

        simpleSelectAllButton.setText("Select All");
        simpleSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        simpleDeselectAllButton.setText("Deselect All");
        simpleDeselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });

        simpleLearnProficiencyButton.setText("Learn Proficiencies");
        simpleLearnProficiencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnProficiencyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout simplePlaneLayout = new javax.swing.GroupLayout(simplePlane);
        simplePlane.setLayout(simplePlaneLayout);
        simplePlaneLayout.setHorizontalGroup(
            simplePlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simplePlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(simplePlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(simplePlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpleCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpleSelectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpleDeselectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpleLearnProficiencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        simplePlaneLayout.setVerticalGroup(
            simplePlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simplePlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(simplePlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(simplePlaneLayout.createSequentialGroup()
                        .addComponent(simpleLearnProficiencyButton)
                        .addGap(18, 18, 18)
                        .addComponent(simpleSelectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(simpleDeselectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(simpleCancelButton)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Simple", simplePlane);

        martialProficiencyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(martialProficiencyList);

        jLabel2.setText("Unknown martial proficiencies:");

        martialSelectAllButton.setText("Select All");
        martialSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        martialDeselectAllButton.setText("Deselect All");
        martialDeselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });

        martialLearnProficiencyButton.setText("Learn Proficiencies");
        martialLearnProficiencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnProficiencyButtonActionPerformed(evt);
            }
        });

        martiaCancelButton.setText("Cancel");
        martiaCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout martialPlaneLayout = new javax.swing.GroupLayout(martialPlane);
        martialPlane.setLayout(martialPlaneLayout);
        martialPlaneLayout.setHorizontalGroup(
            martialPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(martialPlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(martialPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(martialPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(martialSelectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(martialDeselectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(martialLearnProficiencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(martiaCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        martialPlaneLayout.setVerticalGroup(
            martialPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(martialPlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(martialPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addGroup(martialPlaneLayout.createSequentialGroup()
                        .addComponent(martialLearnProficiencyButton)
                        .addGap(18, 18, 18)
                        .addComponent(martialSelectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(martialDeselectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(martiaCancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Martial", martialPlane);

        exoticProficiencyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(exoticProficiencyList);

        exoticCancelButton.setText("Cancel");
        exoticCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Unknown exotic proficiencies:");

        exoticSelectAllButton.setText("Select All");
        exoticSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        exoticDeselectAllButton.setText("Deselect All");
        exoticDeselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });

        exoticLearnProficiencyButton.setText("Learn Proficiencies");
        exoticLearnProficiencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnProficiencyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exoticCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exoticSelectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exoticDeselectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(exoticLearnProficiencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exoticLearnProficiencyButton)
                        .addGap(18, 18, 18)
                        .addComponent(exoticSelectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(exoticDeselectAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(exoticCancelButton)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Exotic", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learnProficiencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnProficiencyButtonActionPerformed
        List selectedValuesList = null;
        if (evt.getSource() == simpleLearnProficiencyButton) {
            selectedValuesList = simpleProficiencyList.getSelectedValuesList();
        } else if (evt.getSource() == martialLearnProficiencyButton) {
            selectedValuesList = martialProficiencyList.getSelectedValuesList();
        } else if (evt.getSource() == exoticLearnProficiencyButton) {
            selectedValuesList = exoticProficiencyList.getSelectedValuesList();
        }
        for (Object o : selectedValuesList) {
            WeaponProficiency ap = (WeaponProficiency) o;
            character.getProficiencies().getWeaponProficiencyList().add(ap);
        }
        parent.refreshDisplayedInformation();
        this.dispose();
    }//GEN-LAST:event_learnProficiencyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        //TODO: verify that this line does what I want
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        JList list = null;
        if (evt.getSource() == simpleSelectAllButton) {
            list = simpleProficiencyList;
        } else if (evt.getSource() == martialSelectAllButton) {
            list = martialProficiencyList;
        } else if (evt.getSource() == exoticSelectAllButton) {
            list = exoticProficiencyList;
        }
        //Select all elements of the list
        int start = 0;
        DefaultListModel model = (DefaultListModel) list.getModel();
        int end = model.getSize() - 1;
        if (end >= 0) {
            list.setSelectionInterval(start, end);
        }
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void deselectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectAllButtonActionPerformed
        if (evt.getSource() == simpleDeselectAllButton) {
            simpleProficiencyList.clearSelection();
        } else if (evt.getSource() == martialDeselectAllButton) {
            martialProficiencyList.clearSelection();
        } else if (evt.getSource() == exoticDeselectAllButton) {
            exoticProficiencyList.clearSelection();
        }
    }//GEN-LAST:event_deselectAllButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton exoticCancelButton;
    private javax.swing.JButton exoticDeselectAllButton;
    private javax.swing.JButton exoticLearnProficiencyButton;
    private javax.swing.JList exoticProficiencyList;
    private javax.swing.JButton exoticSelectAllButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton martiaCancelButton;
    private javax.swing.JToggleButton martialCancelButton;
    private javax.swing.JButton martialDeselectAllButton;
    private javax.swing.JButton martialLearnProficiencyButton;
    private javax.swing.JPanel martialPlane;
    private javax.swing.JList martialProficiencyList;
    private javax.swing.JButton martialSelectAllButton;
    private javax.swing.JToggleButton simpleCancelButton;
    private javax.swing.JButton simpleDeselectAllButton;
    private javax.swing.JButton simpleLearnProficiencyButton;
    private javax.swing.JPanel simplePlane;
    private javax.swing.JList simpleProficiencyList;
    private javax.swing.JButton simpleSelectAllButton;
    // End of variables declaration//GEN-END:variables
}
