package gui.classes;

import character.Player;
import character.classes.CharacterClass;

/**
 *
 * @author Jacob
 */
public class GeneralClassPanel extends javax.swing.JPanel {

    private Player player;
    private CharacterClass cc;

    public GeneralClassPanel(Player player, CharacterClass cc) {
        this.player = player;
        this.cc = cc;
        initComponents();
        //Set class name
        classNameLabel.setText(cc.getName());
        //Set class level
        classLevelLabel.setText("" + player.getClassInfo().getClassLevel(cc));
        int baseAttackBonus = cc.getBaseAttackBonus(player.getClassInfo().getClassLevel(cc));
        baseAttackBonusLabel.setText("" + baseAttackBonus);
    }

    private void updateDisplayedData() {
        classLevelLabel.setText("" + player.getClassInfo().getClassLevel(cc));
        int baseAttackBonus = cc.getBaseAttackBonus(player.getClassInfo().getClassLevel(cc));
        baseAttackBonusLabel.setText("" + baseAttackBonus);
        System.out.println("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        classLevelLabel = new javax.swing.JLabel();
        levelUpButton = new javax.swing.JButton();
        renounceButton = new javax.swing.JButton();
        delevelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        baseAttackBonusLabel = new javax.swing.JLabel();

        classNameLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        classNameLabel.setText("jLabel1");

        jLabel2.setText("Class level:");

        classLevelLabel.setText("1");

        levelUpButton.setText("Level up");
        levelUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelUpButtonActionPerformed(evt);
            }
        });

        renounceButton.setText("Renounce this class");
        renounceButton.setEnabled(false);

        delevelButton.setText("Delevel");
        delevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Base attack bonus:");

        baseAttackBonusLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(baseAttackBonusLabel)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(baseAttackBonusLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delevelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(levelUpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(renounceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(classLevelLabel)))
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classNameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(classLevelLabel))
                        .addGap(28, 28, 28)
                        .addComponent(levelUpButton)
                        .addGap(18, 18, 18)
                        .addComponent(delevelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(renounceButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void levelUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelUpButtonActionPerformed
        int newClassLevel = player.getClassInfo().getClassLevel(cc) + 1;
        player.getClassInfo().setClassLevel(cc, newClassLevel);
        updateDisplayedData();
    }//GEN-LAST:event_levelUpButtonActionPerformed

    private void delevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevelButtonActionPerformed
        int newClassLevel = player.getClassInfo().getClassLevel(cc) - 1;
        player.getClassInfo().setClassLevel(cc, newClassLevel);
        updateDisplayedData();
    }//GEN-LAST:event_delevelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baseAttackBonusLabel;
    private javax.swing.JLabel classLevelLabel;
    private javax.swing.JLabel classNameLabel;
    private javax.swing.JButton delevelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton levelUpButton;
    private javax.swing.JButton renounceButton;
    // End of variables declaration//GEN-END:variables
}
