package gui.defense;

import gui.defense.DefenseArmorClassDialog;
import character.IntegerVerifier;
import character.Player;
import diceroller.DiceRoller;

/**
 *
 * @author Japhez
 */
public final class DefensePanel extends javax.swing.JPanel {

    private Player player;

    public DefensePanel(Player player) {
        initComponents();
        this.player = player;
        prefillInformation();
    }

    public void prefillInformation() {
        //Armor class
        armorClassTextField.setText("" + player.getDefense().getAC());
        touchArmorClassTextField.setText("" + player.getDefense().getACVSTouch());
        flatFootedArmorClassTextField.setText("" + player.getDefense().getACFlatFooted());
        //Saves
        fortitudeSaveTextField.setText("" + player.getDefense().getFortitudeSaveBonus());
        reflexSaveTextField.setText("" + player.getDefense().getReflexSaveBonus());
        willSaveTextField.setText("" + player.getDefense().getWillSaveBonus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        touchArmorClassTextField = new javax.swing.JTextField();
        flatFootedArmorClassTextField = new javax.swing.JTextField();
        uselessLabelName5 = new javax.swing.JLabel();
        uselessLabelName4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        armorClassTextField = new javax.swing.JTextField();
        uselessLabelName6 = new javax.swing.JLabel();
        modifyArmorClassButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fortitudeSaveTextField = new javax.swing.JTextField();
        uselessLabelName2 = new javax.swing.JLabel();
        uselessLabelName1 = new javax.swing.JLabel();
        rollWillButton = new javax.swing.JButton();
        rollFortitudeButton = new javax.swing.JButton();
        willModifierValueTextField = new javax.swing.JTextField();
        reflexModifierValueTextField = new javax.swing.JTextField();
        willSaveTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reflexSaveTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rollReflexButton = new javax.swing.JButton();
        uselessLabelName3 = new javax.swing.JLabel();
        fortModifierValueTextField = new javax.swing.JTextField();
        jButton58 = new javax.swing.JButton();

        touchArmorClassTextField.setEditable(false);

        flatFootedArmorClassTextField.setEditable(false);

        uselessLabelName5.setText("Armor Class VS. Touch:");

        uselessLabelName4.setText("Armor Class:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Armor Class");

        armorClassTextField.setEditable(false);

        uselessLabelName6.setText("Flat-Footed Armor Class:");

        modifyArmorClassButton.setText("Modify Armor Class");
        modifyArmorClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyArmorClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyArmorClassButton)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uselessLabelName5)
                            .addComponent(uselessLabelName4)
                            .addComponent(uselessLabelName6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flatFootedArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(armorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(touchArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uselessLabelName4)
                    .addComponent(armorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uselessLabelName5)
                    .addComponent(touchArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uselessLabelName6)
                    .addComponent(flatFootedArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modifyArmorClassButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setInputVerifier(new IntegerVerifier(-999,999));

        fortitudeSaveTextField.setEditable(false);

        uselessLabelName2.setText("Reflex Save");

        uselessLabelName1.setText("Fortitude Save");

        rollWillButton.setText("Roll Will Save");
        rollWillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollWillButtonActionPerformed(evt);
            }
        });

        rollFortitudeButton.setText("Roll Fortitude Save");
        rollFortitudeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollFortitudeButtonActionPerformed(evt);
            }
        });

        willModifierValueTextField.setText("0");
        willModifierValueTextField.setInputVerifier(new IntegerVerifier(-999,999));

        reflexModifierValueTextField.setText("0");
        reflexModifierValueTextField.setInputVerifier(new IntegerVerifier(-999,999));

        willSaveTextField.setEditable(false);

        jLabel2.setText("Misc Modifier");

        reflexSaveTextField.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Saving Throws");

        rollReflexButton.setText("Roll Reflex Save");
        rollReflexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollReflexButtonActionPerformed(evt);
            }
        });

        uselessLabelName3.setText("Will Save");

        fortModifierValueTextField.setText("0");
        fortModifierValueTextField.setInputVerifier(new IntegerVerifier(-999,999));

        jButton58.setText("View Breakdown");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uselessLabelName3)
                            .addComponent(uselessLabelName1)
                            .addComponent(uselessLabelName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(willSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reflexSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fortitudeSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(fortModifierValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(reflexModifierValueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(willModifierValueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollWillButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollFortitudeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rollReflexButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton58, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollFortitudeButton)
                    .addComponent(uselessLabelName1)
                    .addComponent(fortModifierValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fortitudeSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollReflexButton)
                    .addComponent(uselessLabelName2)
                    .addComponent(reflexModifierValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reflexSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollWillButton)
                    .addComponent(uselessLabelName3)
                    .addComponent(willModifierValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(willSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton58)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fortitudeSaveTextField.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rollFortitudeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollFortitudeButtonActionPerformed
        int result = DiceRoller.rollD20() + Integer.parseInt(fortitudeSaveTextField.getText()) + Integer.parseInt(fortModifierValueTextField.getText());
        System.out.println("Fortitude save: " + result);
    }//GEN-LAST:event_rollFortitudeButtonActionPerformed

    private void rollReflexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollReflexButtonActionPerformed
        int result = DiceRoller.rollD20() + Integer.parseInt(reflexSaveTextField.getText()) + Integer.parseInt(reflexModifierValueTextField.getText());
        System.out.println("Reflex save: " + result);
    }//GEN-LAST:event_rollReflexButtonActionPerformed

    private void rollWillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollWillButtonActionPerformed
        int result = DiceRoller.rollD20() + Integer.parseInt(willSaveTextField.getText()) + Integer.parseInt(willModifierValueTextField.getText());
        System.out.println("Will save: " + result);
    }//GEN-LAST:event_rollWillButtonActionPerformed

    private void modifyArmorClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyArmorClassButtonActionPerformed
        DefenseArmorClassDialog defenseArmorClassDialog = new DefenseArmorClassDialog(this, player);
        defenseArmorClassDialog.setVisible(true);
    }//GEN-LAST:event_modifyArmorClassButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField armorClassTextField;
    private javax.swing.JTextField flatFootedArmorClassTextField;
    private javax.swing.JTextField fortModifierValueTextField;
    private javax.swing.JTextField fortitudeSaveTextField;
    private javax.swing.JButton jButton58;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modifyArmorClassButton;
    private javax.swing.JTextField reflexModifierValueTextField;
    private javax.swing.JTextField reflexSaveTextField;
    private javax.swing.JButton rollFortitudeButton;
    private javax.swing.JButton rollReflexButton;
    private javax.swing.JButton rollWillButton;
    private javax.swing.JTextField touchArmorClassTextField;
    private javax.swing.JLabel uselessLabelName1;
    private javax.swing.JLabel uselessLabelName2;
    private javax.swing.JLabel uselessLabelName3;
    private javax.swing.JLabel uselessLabelName4;
    private javax.swing.JLabel uselessLabelName5;
    private javax.swing.JLabel uselessLabelName6;
    private javax.swing.JTextField willModifierValueTextField;
    private javax.swing.JTextField willSaveTextField;
    // End of variables declaration//GEN-END:variables
}
